/* eslint-disable react/jsx-props-no-spreading */
import {
    AccountBalance,
    AccountBalanceWalletOutlined,
    AccountCircle,
    Add,
    AddCircle,
    AddCircleOutline,
    Adjust,
    Assignment,
    AttachMoney,
    AutoGraph,
    Autorenew,
    BatteryChargingFullOutlined,
    CalculateOutlined,
    CallMerge,
    CallSplit,
    Check,
    CheckCircle,
    CheckOutlined,
    ChevronRight,
    Circle,
    Close,
    CloudUpload,
    Code,
    ContentCopy,
    CopyAllOutlined,
    CreditCard,
    Dashboard,
    Delete,
    Description,
    DesktopWindowsOutlined,
    DirectionsWalk,
    DoubleArrow,
    Download,
    Edit,
    Email,
    ExpandLess,
    ExpandMore,
    Face,
    FilterDrama,
    FindInPage,
    FlashOnOutlined,
    Flip,
    Folder,
    FolderOpen,
    FolderOutlined,
    FormatLineSpacing,
    FormatListBulleted,
    Forward,
    GridOn,
    GroupAdd,
    GroupsRounded,
    Help,
    Info,
    InfoOutlined,
    Input,
    InsertChart,
    InsertDriveFile,
    Keyboard,
    Label,
    Language,
    Layers,
    LibraryAdd,
    Link,
    LiveHelp,
    LocationOn,
    Lock,
    LooksOne,
    Memory,
    Message,
    ModeComment,
    MonetizationOnOutlined,
    MonetizationOnRounded,
    MoreHoriz,
    MoreVert,
    NorthEastOutlined,
    NoteAdd,
    OpenInBrowser,
    OpenInNew,
    OpenWith,
    PauseCircleOutlined,
    People,
    Person,
    PlayArrow,
    PlayCircleOutlined,
    PowerSettingsNew,
    Print,
    Public,
    Publish,
    RadioButtonChecked,
    RadioButtonUnchecked,
    Receipt,
    ReceiptRounded,
    ReduceCapacityRounded,
    Replay,
    SavedSearch,
    School,
    Search,
    Settings,
    SettingsApplications,
    SettingsSystemDaydream,
    Share,
    SignalCellularNoSim,
    Star,
    StarOutline,
    Stop,
    SupportAgent,
    SvgIconComponent,
    SwapCalls,
    SwapVert,
    Sync,
    SystemUpdateAlt,
    Terminal,
    Toc,
    UnfoldLess,
    UnfoldMore,
    ViewColumn,
    Visibility,
    VisibilityOff,
    Widgets,
    WifiTethering,
    WorkspacesOutlined,
    WrapText,
    YoutubeSearchedFor,
} from "@mui/icons-material";
import { SvgIconProps } from "@mui/material";
import { useTheme } from "@mui/material/styles";
import React from "react";

export type IconByNameProps = SvgIconProps & {
    name: string;
    rotateDegrees?: number;
};

function rotateIcon(IconComponent: SvgIconComponent, degrees: number) {
    function RotatedIcon(props: IconByNameProps) {
        const { sx } = props;

        return <IconComponent {...props} sx={{ transform: `rotate(${degrees}deg)`, ...sx }} />;
    }

    return RotatedIcon;
}

const iconComponentMap: Record<string, SvgIconComponent | ReturnType<typeof rotateIcon>> = {
    accounts: People,
    add: Add,
    addCircle: AddCircle,
    addCircleOutline: AddCircleOutline,
    account: Person,
    accountsAdd: GroupAdd,
    advancedSearch: YoutubeSearchedFor,
    accountBalanceWalletOutlined: AccountBalanceWalletOutlined,
    accountCircle: AccountCircle,
    arrowRightTop: NorthEastOutlined,
    arrows: OpenWith,
    autoGraph: AutoGraph,
    assignment: Assignment,
    balance: AccountBalance,
    batteryFlash: BatteryChargingFullOutlined,
    calculateOutlined: CalculateOutlined,
    card: CreditCard,
    changeType: Edit,
    charge: Receipt,
    chart: InsertChart,
    clone: CopyAllOutlined,
    check: Check,
    checkOutlined: CheckOutlined,
    checkCircle: CheckCircle,
    circle: Circle,
    circleOutlined: RadioButtonUnchecked,
    close: Close,
    cloudOutlineAlt: FilterDrama,
    cloudUpload: CloudUpload,
    code: Code,
    collapse: ExpandLess,
    columns: ViewColumn,
    comment: ModeComment,
    copy: ContentCopy,
    copyPath: ContentCopy,
    create: Add,
    createJob: OpenInNew,
    createSet: FolderOpen,
    dashboard: Dashboard,
    default: Star,
    delete: Delete,
    desktopWindows: DesktopWindowsOutlined,
    download: Download,
    dropbox: SettingsSystemDaydream,
    doubleArrow: DoubleArrow,
    edit: Edit,
    email: Email,
    execute: PlayArrow,
    expand: ExpandMore,
    group: GroupsRounded,
    eye: Visibility,
    favorite: Star,
    face: Face,
    file: InsertDriveFile,
    fileText: Description,
    filePlus: NoteAdd,
    flash: FlashOnOutlined,
    flatten: GridOn,
    flip: Flip,
    folder: Folder,
    folderOutlined: FolderOutlined,
    fork: CallSplit,
    forkRotated: rotateIcon(CallSplit, 180),
    formatListBulleted: FormatListBulleted,
    forum: LiveHelp,
    globe: Public,
    globeAlt: Language,
    graduationCap: School,
    go: ChevronRight,
    help: Help,
    import: CloudUpload,
    importFromBank: AccountBalance,
    info: Info,
    infoOutlined: InfoOutlined,
    invite: Add,
    join: GroupAdd,
    keyboard: Keyboard,
    layers: Layers,
    leave: DirectionsWalk,
    link: Link,
    location: LocationOn,
    lock: Lock,
    makeAdmin: ExpandLess,
    makePrivate: VisibilityOff,
    moreVert: MoreVert,
    moreHoriz: MoreHoriz,
    makePublic: Visibility,
    memory: Memory,
    merge: CallMerge,
    mergeRotated: rotateIcon(CallMerge, 180),
    message: Message,
    money: AttachMoney,
    moveToProject: Forward,
    moveToSet: Input,
    monetization: MonetizationOnRounded,
    monetizationOutlined: MonetizationOnOutlined,
    oneSquare: LooksOne,
    open: Visibility,
    openExternalProject: Folder,
    pauseOutlined: PauseCircleOutlined,
    palyOutlined: PlayCircleOutlined,
    people: People,
    power: PowerSettingsNew,
    preview: Visibility,
    print: Print,
    proSearch: SavedSearch,
    purge: SignalCellularNoSim,
    read: Toc,
    reduceCapacity: ReduceCapacityRounded,
    refresh: Autorenew,
    remove: Delete,
    resubmit: Replay,
    revokeAccess: VisibilityOff,
    revokeAdmin: ExpandLess,
    run: PlayArrow,
    receipt: ReceiptRounded,
    search: Search,
    quickSearch: Search,
    globalSearch: Search,
    searchGlobal: FindInPage,
    selectItems: LibraryAdd,
    selectFiles: LibraryAdd,
    setDefault: StarOutline,
    setIndex: FormatLineSpacing,
    settings: Settings,
    settingsSquare: SettingsApplications,
    share: GroupAdd,
    shareWithMe: Share,
    show: ExpandLess,
    source: InsertDriveFile,
    squareDown: SystemUpdateAlt,
    stop: Stop,
    subworkflow: Adjust,
    supportAgent: SupportAgent,
    sync: Sync,
    swapAlt: SwapCalls,
    swapVertical: SwapVert,
    tag: Label,
    terminate: Stop,
    terminal: Terminal,
    update: Autorenew,
    upload: Publish,
    unfoldLess: UnfoldLess,
    unfoldMore: UnfoldMore,
    visualize: OpenInBrowser,
    widgets: Widgets,
    workspaces: WorkspacesOutlined,
    wifiTethering: WifiTethering,
    workflow: RadioButtonChecked,
    wrapText: WrapText,
};

export default function IconByName({
    name = "circle",
    rotateDegrees = 0,
    sx = {},
    ...iconProps
}: IconByNameProps) {
    const theme = useTheme();
    const IconComponent = iconComponentMap[name];
    const iconStyle = { fontSize: theme.iconDefaultFontSize, transform: "", ...sx };

    if (rotateDegrees) iconStyle.transform = `rotate(${rotateDegrees}deg)`;
    if (IconComponent) return <IconComponent {...iconProps} sx={iconStyle} name={name} />;

    return <Circle {...iconProps} />;
}
